# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://walkerfeng.com
date_format: "ordinal"
title: Walker的博客
subtitle: ""
description: "Walker的个人博客"
keywords: Walker,walkerfeng
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Walker
organization: 
organization_url: 
github_username: walkerfeng
location: Shenzhen, China
email: walker@walkerfeng.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: walkerfeng/walkerfeng.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: 
    repo: 
    oauth:
        client_id: 
        client_secret: 
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: walkerfeng
    repo: walker-blog-comments
    clientID: 251fcf444669be13b664
    clientSecret: f58d765a2b9396546ceab8919e1c342322a833e6
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: 
